"""
radius=float(input("enter radius"))
area=3.142*(radius**2)
print(area)
"""

"""
base=float(input("what is the base of your triangle"))# we are using function called input()
height=input("what is the height of your triangle")#

radius=float(input("enter a radius to calculate the area of circle"))
area=3.142*radius*radius
print("The area is as follows:",area)
"""
"""
mpg=float(input("enter the fuel economy for your car"))
fuelamount=float(input("enter the amount of fuel you have in your car"))
distance=mpg*fuelamount
print(distance)
"""
#Write a program which asks for a length & height for a rectangle. It should
#calculate the area of the rectangle and display it. It should also calculate the parameter of the rectangle and display that. 
"""
base=float(input("enter the amount of base"))
height=float(input("enter the amount of height"))
rectanglearea=base*height
print(rectanglearea)

#task 1
number1=23
number2=9

print(number1+number2)

print(number1-number2)

print(number1/number2)

print(number1*number2)

print(number1//number2)

print(number1%number2)